### PR TITLE
Basic support for topics

### LINKED ISSUE #7: Support for topics?
Curious if you plan on adding support for subscribing and unsubscribing to topics?

### PR DESCRIPTION
**Pull request by abiskop**
fixes #7

### CODE REVIEW

**Comment by evanshortiss** [comment]
This looks great @abiskop. I've been busy with work the last few days but should get around to merging this tonight.

**Comment by evanshortiss** [comment]
@abiskop could you possibly update the README with information on the newly added features?

**Comment by abiskop** [comment]
Sure! Will do that tomorrow!

**Comment by evanshortiss** [comment]
Thanks for the update @abiskop. I can relate :)

**Comment by abiskop** [comment]
Alright, README update done!

**Comment by evanshortiss** [comment]
This is an awesome PR thanks @abiskop! I'll get it published to npm within 24 hours.

:clap:

**Comment by evanshortiss** [comment]
@abiskop published to npm registry as version 1.2.0

**Comment by abiskop** [comment]
Great, thanks! I might also add the remaining topic-/subscription-related methods like "getTopicAttributes" and stuff at some point; I just didn't really need it at this point, that's why I skipped it during the first iteration.
Also, I realized that in many cases, one does not actually need to know the platform(Application(Arn)), e.g. for creating topics, subscribing users etc.; however, it is strictly required that it is passed into the constructor when creating an instance of the interface. We might consider changing the API here at some point so that the platform has to be passed only into methods that actually need it...

**Comment by evanshortiss** [comment]
Add things as we need. The evolutionary development process ;)

**Comment by race** [comment]
(thumbsup)

**Pull request merged**
